export const Events = {
	LOAD_DATA: "LOAD_DATA",
	LOAD_DATA_FULFILLED: "LOAD_DATA_FULFILLED",
	LOAD_DATA_REJECTED: "LOAD_DATA_FULFILLED",
	CLEAR_GET_ALL_STUDENTS: "CLEAR_GET_ALL_STUDENTS",
	LOAD_STUDENT: "LOAD_STUDENT",
	LOAD_STUDENT_FULFILLED: "LOAD_STUDENT_FULFILLED",
	DELETE_USER: "DELETE_USER",
	DELETE_USER_FULFILLED: "DELETE_USER_FULFILLED",
	DELETE_USER_REJECTED: "DELETE_USER_REJECTED",
	CLEAR_DELETE_STUDENTS: "CLEAR_DELETE_STUDENTS",
	EDIT_USER: "EDIT_USER",
	EDIT_USER_FULFILLED: "EDIT_USER_FULFILLED",
	EDIT_USER_REJECTED: "EDIT_USER_REJECTED",
	CLEAR_EDIT_USER: "CLEAR_EDIT_USER"
};